version: "3"

services:
  quakeledger:
    image: gfzriesgos/quakeledger:latest

  shakyground:
    image: gfzriesgos/shakyground:latest

  assetmaster:
    image: gfzriesgos/assetmaster:latest

  modelprop:
    image: gfzriesgos/modelprop:latest

  deus:
    image: gfzriesgos/deus:latest

  flooddamage:
    image: gfzriesgos/flooddamage:latest

  riesgos-wps:
    image: gfzriesgos/riesgos-wps:latest
    container_name: riesgos-wps-dev
    ports:
      - "8080:8080"
    volumes:
      - "riesgos-json-config-dev:/usr/share/riesgos/json-configurations"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "riesgos-wps-config-dev:/usr/local/tomcat/webapps/wps/WEB-INF/classes/db/data"

volumes:
  riesgos-json-config-dev:
    external: true
  riesgos-wps-config-dev:
    external: true

networks:
  network:
    external:
      name: main_network
